// Generated by CoffeeScript 1.7.1
(function() {
  window.GoogleAnalytics = (function() {
    function _Class() {}

    _Class.trackEvent = function(o) {
      if (window._gaq) {
        _gaq.push(['_trackEvent', o.category, o.action]);
      }
      if (window.ga) {
        return ga('send', {
          hitType: 'event',
          eventCategory: o.category,
          eventAction: o.action
        });
      }
    };

    _Class.trackSocial = function(o) {
      if (!o.href) {
        o.href = window.location.href;
      }
      if (window._gaq) {
        _gaq.push(['_trackSocial', o.network, o.action, o.target, o.href]);
      }
      if (window.ga) {
        return ga('send', {
          hitType: 'social',
          socialNetwork: o.network,
          socialAction: o.action,
          socialTarget: o.target,
          page: o.href
        });
      }
    };

    return _Class;

  })();

}).call(this);
