// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    $.fn.fadeUp = function(speed, callback) {
      return this.each(function() {
        if (typeof speed === "function") {
          callback = speed;
          speed = "normal";
        }
        return $(this).slideUp(speed, callback).animate({
          opacity: 0
        }, {
          queue: false,
          duration: speed,
          complete: function() {
            return $(this).css('opacity', '');
          }
        });
      });
    };
    return $.fn.fadeDown = function(speed, callback) {
      return this.each(function() {
        var opacity;
        if (typeof speed === "function") {
          callback = speed;
          speed = "normal";
        }
        opacity = $(this).css('opacity') || 1;
        return $(this).slideDown(speed, callback).css({
          opacity: 0
        }).animate({
          opacity: opacity
        }, {
          queue: false,
          duration: speed,
          complete: function() {
            return $(this).css('opacity', '');
          }
        });
      });
    };
  })(jQuery);

}).call(this);
