// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    var hideScroll, showScroll;
    hideScroll = function() {
      var oldWidth;
      oldWidth = $('body').width();
      $('body').css({
        overflow: 'hidden'
      });
      return $('body').css({
        paddingRight: $('body').width() - oldWidth
      });
    };
    showScroll = function() {
      return $('body').css({
        overflow: '',
        paddingRight: ''
      });
    };
    return window.Popup = (function() {
      function _Class(classes, $body) {
        if (classes == null) {
          classes = "";
        }
        if ($body == null) {
          $body = null;
        }
        this.popup = $("<div class='popup'><div><div><div class='popup-page " + classes + "'></div></div></div></div>");
        this.popup.appendTo(window.document.body);
        this.popup.find('.popup-page').append('<a class="close close-popup">×</a>');
        if ($body) {
          this.popup.find('.popup-page').append($body);
          this.show();
        }
        this.popup.on('click', '.close-popup', (function(_this) {
          return function() {
            return _this.close();
          };
        })(this));
        this.popup.click((function(_this) {
          return function(e) {
            if ($(e.target).parents('.popup-page').length) {
              return;
            }
            if ($(e.target).hasClass('popup-page')) {
              return;
            }
            return _this.close();
          };
        })(this));
      }

      _Class.prototype.setBody = function($body) {
        return this.popup.find('.popup-page').html('').append('<a class="close close-popup">×</a>').append($body);
      };

      _Class.prototype.close = function(callback) {
        return this.popup.fadeOut((function(_this) {
          return function() {
            showScroll();
            if (typeof callback === "function") {
              return callback.call(_this);
            }
          };
        })(this));
      };

      _Class.prototype.show = function(callback) {
        hideScroll();
        return this.popup.hide().fadeIn((function(_this) {
          return function() {
            if (typeof callback === "function") {
              return callback.call(_this);
            }
          };
        })(this));
      };

      return _Class;

    })();
  })(jQuery);

}).call(this);
